spring:
  application:
    name: IdealHome

server:
  port: 8081

logging:
  level:
    org.springframework: INFO

idealista:
  url: ${IDEALISTA_API}
  secret: ${IDEALISTA_SECRET}
  key: ${IDEALISTA_KEY}