spring:
  application:
    name: IdealHome
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: BASIC
      httpclient:
        hc5:
          enabled: true


server:
  port: 8081

logging:
  level:
    org.springframework: INFO
    com.api.idealhome: DEBUG

notion:
  url: ${NOTION_URL}
  key: ${NOTION_KEY}
  version: ${NOTION_API_VERSION}
  grantType: ${NOTION_GRANT_TYPE}
  scope: ${NOTION_SCOPE}
  dataBaseId: ${NOTION_DATABASE_ID}
  dataBaseUrl: ${NOTION_DATABASE_URL}

telegram:
  url: ${TELEGRAM_URL}
  key: ${TELEGRAM_KEY}
  chatId: ${TELEGRAM_CHAT_ID}

idealista:
  url: ${IDEALISTA_URL}
  secret: ${IDEALISTA_SECRET}
  key: ${IDEALISTA_KEY}
  grantType: ${IDEALISTA_GRANT_TYPE}
  scope: ${IDEALISTA_SCOPE}
  version: ${IDEALISTA_API_VERSION}
  filters:
    center: ${IDEALISTA_CENTER_FILTER}
    maxPrice: ${IDEALISTA_MAX_PRICE_FILTER}
    operation: "sale"
    country: "pt"
    propertyType: "homes"
    distance: 30000
    locale: "pt"
    maxItems: 50
    isParkingSpaceIncluded: true
    bathrooms: 2
    elevator: true
    size: 90
    sinceDate: Y
  customFilters:
    minimumRooms: 2
    province: ${PROVINCE}
    notInterestedMunicipality: ${NOT_INTERESTED_MUNICIPALITY}